name: Calculate MP19 Quality Gate Rate

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00 UTC
  workflow_dispatch:      # Permette di lanciarlo manualmente per testare

jobs:
  compute-mp19-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Riutilizziamo la action custom del tuo team
      # Questa si occupa di setup python e pip install -r requirements.txt
      - name: Setup Python with Dependencies
        uses: ./.github/actions/setup-python-metric
        with:
          metric-directory: quality-gate

      - name: Run MP19 Script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
          GITHUB_ORG: ${{ github.repository_owner }}
          
        run: python quality-gate/quality-gate.py