name: Calculate The Time Efficiency

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00
  workflow_dispatch:

jobs:
  compute-time-efficiency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python with Dependencies
        uses: ./.github/actions/setup-python-metric
        with:
          metric-directory: time-efficiency

      - name: Run Script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
          GITHUB_ORG: ${{ github.repository_owner }}
          JIRA_URL: "https://notipswe.atlassian.net"
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: "NT"
          JIRA_SPRINT_NAME: "NT Sprint 6"
        run: python time-efficiency/time-efficiency.py
